"""Generate the Step 42 synthetic demo and a media-backed 15-second preview.

Synthetic clips are labeled as test media. Replace files in the media root and
rewrite sha256/bytes in the manifest to use your own footage. No downloads.
"""
import json
import subprocess
from pathlib import Path

from vicekrack.artifact_binding import sha256_bytes
from vicekrack.orchestrator import ROOT, read_json
from vicekrack.preview import render_preview
from vicekrack.scene_plan import build_scene_plan

ROOT_OUT = ROOT / "runtime" / "step42-demo"
MEDIA = ROOT_OUT / "media"


def ffmpeg(*args):
    subprocess.run(["ffmpeg", "-y", *args], check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def main():
    MEDIA.mkdir(parents=True, exist_ok=True)
    plan = build_scene_plan(read_json(ROOT / "examples/short-script-cooking.json"))
    (ROOT_OUT / "scene-plan.json").write_text(json.dumps(plan, indent=2) + "\n", encoding="utf-8")
    colors = ("0x1d4ed8", "0x047857", "0xb45309", "0x7c3aed")
    assets, assignments = [], []
    for scene, color in zip(plan["scenes"], colors):
        index = scene["index"]
        duration = scene["beat"]["end_seconds"] - scene["beat"]["start_seconds"]
        if index < 4:
            name = f"synthetic-scene-{index}.mp4"
            ffmpeg("-f", "lavfi", "-i", f"color=c={color}:s=1280x720:d={duration + 2}",
                   "-c:v", "libx264", "-pix_fmt", "yuv420p", str(MEDIA / name))
            extra = {"trim": {"start_seconds": 0.5, "end_seconds": 0.5 + duration}}
            kind = "video"
        else:
            name = f"synthetic-scene-{index}.png"
            ffmpeg("-f", "lavfi", "-i", f"color=c={color}:s=1080x1920", "-frames:v", "1", str(MEDIA / name))
            extra = {"image_duration_seconds": duration}
            kind = "image"
        data = (MEDIA / name).read_bytes()
        assets.append({
            "asset_id": f"synthetic-{index}",
            "relative_path": name,
            "kind": kind,
            "sha256": sha256_bytes(data),
            "bytes": len(data),
            "provenance": {"label": "synthetic_test_media", "note": "Generated by scripts/step42_demo.py. Not real footage."},
            "rights": {"status": "declared_not_verified",
                       "declaration": "Synthetic test media generated for the Step 42 demo. Not a rights clearance.",
                       "declared_by": "step42-demo"},
        })
        assignments.append({"scene_index": index, "asset_id": f"synthetic-{index}",
                            "fit": "cover" if index != 2 else "contain",
                            "anchor": "center" if index != 3 else "top", **extra})
    manifest = {"contract": "media_manifest", "version": "1.0", "manifest_id": "step42-synthetic-demo",
                "plan_id": plan["plan_id"], "mute_source_audio": True, "assets": assets, "assignments": assignments}
    (ROOT_OUT / "media-manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    result = render_preview(plan, directory=ROOT_OUT / "previews", media=manifest, media_root=MEDIA)
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
